// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:
        'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // TODO(CURSOR): Thay bằng API key thực
    appId:
        '1:123456789:web:abcdef123456', // TODO(CURSOR): Thay bằng App ID thực
    messagingSenderId: '123456789', // TODO(CURSOR): Thay bằng Sender ID thực
    projectId: 'spend-sage-app', // TODO(CURSOR): Thay bằng Project ID thực
    authDomain:
        'spend-sage-app.firebaseapp.com', // TODO(CURSOR): Thay bằng Auth Domain thực
    storageBucket:
        'spend-sage-app.appspot.com', // TODO(CURSOR): Thay bằng Storage Bucket thực
    measurementId:
        'G-XXXXXXXXXX', // TODO(CURSOR): Thay bằng Measurement ID thực
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvZrp0moYfVzq0bBUoBNm15GMe4Fe-Q7g',
    appId: '1:19638187607:android:549470e65bebbd0a561512',
    messagingSenderId: '19638187607',
    projectId: 'doanltdd-46bd4',
    storageBucket: 'doanltdd-46bd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:
        'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // TODO(CURSOR): Thay bằng API key thực
    appId:
        '1:123456789:ios:abcdef123456', // TODO(CURSOR): Thay bằng App ID thực
    messagingSenderId: '123456789', // TODO(CURSOR): Thay bằng Sender ID thực
    projectId: 'spend-sage-app', // TODO(CURSOR): Thay bằng Project ID thực
    storageBucket:
        'spend-sage-app.appspot.com', // TODO(CURSOR): Thay bằng Storage Bucket thực
    iosBundleId:
        'com.example.spendSage', // TODO(CURSOR): Thay bằng Bundle ID thực
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey:
        'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // TODO(CURSOR): Thay bằng API key thực
    appId:
        '1:123456789:ios:abcdef123456', // TODO(CURSOR): Thay bằng App ID thực
    messagingSenderId: '123456789', // TODO(CURSOR): Thay bằng Sender ID thực
    projectId: 'spend-sage-app', // TODO(CURSOR): Thay bằng Project ID thực
    storageBucket:
        'spend-sage-app.appspot.com', // TODO(CURSOR): Thay bằng Storage Bucket thực
    iosBundleId:
        'com.example.spendSage', // TODO(CURSOR): Thay bằng Bundle ID thực
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey:
        'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx', // TODO(CURSOR): Thay bằng API key thực
    appId:
        '1:123456789:web:abcdef123456', // TODO(CURSOR): Thay bằng App ID thực
    messagingSenderId: '123456789', // TODO(CURSOR): Thay bằng Sender ID thực
    projectId: 'spend-sage-app', // TODO(CURSOR): Thay bằng Project ID thực
    authDomain:
        'spend-sage-app.firebaseapp.com', // TODO(CURSOR): Thay bằng Auth Domain thực
    storageBucket:
        'spend-sage-app.appspot.com', // TODO(CURSOR): Thay bằng Storage Bucket thực
    measurementId:
        'G-XXXXXXXXXX', // TODO(CURSOR): Thay bằng Measurement ID thực
  );
}
